name: haunt
description: Haunt Flame Game

dependencies:
  flutter:
    sdk: flutter

  flame:
      path: ../flame

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/layers/layer_01_1920x1080.png
    - assets/images/layers/layer_02_1920x1080.png
    - assets/images/layers/layer_03_1920x1080.png
    - assets/images/layers/layer_04_1920x1080.png
    - assets/images/layers/layer_05_1920x1080.png
    - assets/images/layers/layer_06_1920x1080.png
    - assets/images/layers/layer_07_1920x1080.png

